### ISSUE TITLE
Add Menus from Firebase

### ISSUE THREAD

**Issue by DonkeyKongJr** [DonkeyKongJr/pimlify#15]
After selecting a restaurant the application should route to the menu view and retrieve all menu items from a specific firestore collection.

The collection id should be passed as param to the menu component. If no id is available the route should be redirected to home.

**Comment by DonkeyKongJr** [comment]
Proposed menu struct.

name: string
description: string
price: number
validFrom: timestamp
validTo: timestamp

**Comment by Opiskull** [comment]
what do we need validfrom validto for?

**Comment by DonkeyKongJr** [comment]
Thought about multiple different menu which are valid from different times. Could be used for historical data as well, but could also be added later on tbh.

**Comment by Opiskull** [comment]
I'm working on that right now :)

**Comment by Opiskull** [comment]
i Will close this issue... as we are loading the menus from firebase
