### ISSUE TITLE
CD: Firebase Deployment

### ISSUE THREAD

**Issue by DonkeyKongJr** [DonkeyKongJr/pimlify#39]
**Is your feature request related to a problem? Please describe.**
Add automatic firebase deployment to travis ci when execution a build on the master branch.

**Comment by DonkeyKongJr** [comment]
@Opiskull how do we provide the firebase configuration? Pushing it to the repository or are there any better alternatives?

**Comment by Opiskull** [comment]
hm... no idea... are there conventions somewhere? how are other people doing it?

**Comment by DonkeyKongJr** [comment]
There seems to be no correct answer, however as we know every client needs to know the firebase config to connect to the services and they are exposed anyways. Since we allow only calls to our ressources from authenticated users it seems to be fine to put the config in the repository.

https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public

**Comment by DonkeyKongJr** [comment]
Config was added in #45 from @Opiskull ^^

**Comment by DonkeyKongJr** [comment]
Fixed with fixing build config by adding index.html
