### ISSUE TITLE
Add Unit Test Framework and sample test

### ISSUE THREAD

**Issue by DonkeyKongJr** [DonkeyKongJr/pimlify#42]
**Is your feature request related to a problem? Please describe.**
Through our high quality standards we need unit testing in our application. 

**Describe the solution you'd like**
The first testing framework we should look at is JEST. It seems to be the fastest our there. In Addition to that our Sonar Quality Gate is set to a minimum of 80% Code Coverage to pass.

**Describe alternatives you've considered**
We should discuss alternatives if JEST doesn't meet our requirements or standards.

**Comment by DonkeyKongJr** [comment]
Including components in tests fail with

>     TypeError: Class extends value undefined is not a constructor or null

Have to look closer after closing issue #43

**Comment by Opiskull** [comment]
closed. should work now
